name: hello world
on:
  push: 
    branches: [main]
jobs:
  say-hello:
      runs-on: windows-latest
      steps:
        -run: echo "TODAY = $(date + %y-%m-%d)" >> %GITHUB_ENV
        - run: echo Hello world, today is $TODAY